// Generated by scripts/embed-idl.mjs from src/idl/solsocket_engine.json — do not edit.
export const IDL = {
  address: "CrLS1Ry58q59AgmqbNVrqbfs2bWGJtjk12PezXh4LeYh",
  metadata: {
    name: "solsocket_engine",
    version: "0.1.0",
    spec: "0.1.0",
    description: "Generic realtime room engine for Solana + MagicBlock Ephemeral Rollups",
  },
  instructions: [
    {
      name: "close_presence",
      docs: [
        "Reclaim a presence slot's rent. Base layer only, after undelegation;",
        "only the wallet that joined may close it.",
      ],
      discriminator: [201, 222, 39, 160, 72, 191, 225, 7],
      accounts: [
        {
          name: "presence",
          writable: true,
        },
        {
          name: "player",
          writable: true,
          signer: true,
        },
      ],
      args: [],
    },
    {
      name: "close_room",
      docs: [
        "Reclaim the room's rent. Base layer only, after undelegation; creator only.",
      ],
      discriminator: [152, 197, 88, 192, 98, 197, 51, 211],
      accounts: [
        {
          name: "room",
          writable: true,
        },
        {
          name: "creator",
          writable: true,
          signer: true,
        },
      ],
      args: [],
    },
    {
      name: "commit_room",
      docs: [
        "Checkpoint the room's ER state to the base layer (stays delegated).",
        "Any member may checkpoint; it only persists what the ER already holds.",
      ],
      discriminator: [138, 145, 121, 138, 83, 230, 52, 13],
      accounts: [
        {
          name: "payer",
          writable: true,
          signer: true,
        },
        {
          name: "room",
          writable: true,
        },
        {
          name: "magic_program",
          address: "Magic11111111111111111111111111111111111111",
        },
        {
          name: "magic_context",
          writable: true,
          address: "MagicContext1111111111111111111111111111111",
        },
      ],
      args: [],
    },
    {
      name: "create_room",
      docs: [
        "Create a room. The room PDA is keyed by (creator, room_id) so ids only",
        "need to be unique per creator, never globally.",
      ],
      discriminator: [130, 166, 32, 2, 247, 120, 178, 53],
      accounts: [
        {
          name: "room",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "const",
                value: [114, 111, 111, 109],
              },
              {
                kind: "account",
                path: "creator",
              },
              {
                kind: "arg",
                path: "room_id",
              },
            ],
          },
        },
        {
          name: "creator",
          writable: true,
          signer: true,
        },
        {
          name: "system_program",
          address: "11111111111111111111111111111111",
        },
      ],
      args: [
        {
          name: "room_id",
          type: "u64",
        },
        {
          name: "max_players",
          type: "u16",
        },
        {
          name: "initial_state",
          type: "bytes",
        },
      ],
    },
    {
      name: "delegate_presence",
      docs: ["Delegate a presence slot to the same ER as its room. Base layer."],
      discriminator: [70, 68, 222, 55, 169, 250, 156, 155],
      accounts: [
        {
          name: "payer",
          signer: true,
        },
        {
          name: "buffer_pda",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "const",
                value: [98, 117, 102, 102, 101, 114],
              },
              {
                kind: "account",
                path: "pda",
              },
            ],
            program: {
              kind: "const",
              value: [
                176, 19, 252, 153, 174, 29, 63, 9, 201, 203, 137, 179, 81, 231, 32, 187,
                243, 140, 183, 251, 61, 108, 118, 234, 137, 194, 199, 179, 144, 52, 237,
                138,
              ],
            },
          },
        },
        {
          name: "delegation_record_pda",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "const",
                value: [100, 101, 108, 101, 103, 97, 116, 105, 111, 110],
              },
              {
                kind: "account",
                path: "pda",
              },
            ],
            program: {
              kind: "account",
              path: "delegation_program",
            },
          },
        },
        {
          name: "delegation_metadata_pda",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "const",
                value: [
                  100, 101, 108, 101, 103, 97, 116, 105, 111, 110, 45, 109, 101, 116, 97,
                  100, 97, 116, 97,
                ],
              },
              {
                kind: "account",
                path: "pda",
              },
            ],
            program: {
              kind: "account",
              path: "delegation_program",
            },
          },
        },
        {
          name: "pda",
          writable: true,
        },
        {
          name: "owner_program",
          address: "CrLS1Ry58q59AgmqbNVrqbfs2bWGJtjk12PezXh4LeYh",
        },
        {
          name: "delegation_program",
          address: "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh",
        },
        {
          name: "system_program",
          address: "11111111111111111111111111111111",
        },
      ],
      args: [
        {
          name: "room",
          type: "pubkey",
        },
        {
          name: "player",
          type: "pubkey",
        },
      ],
    },
    {
      name: "delegate_room",
      docs: [
        "Delegate a room to an Ephemeral Rollup. Base layer. The target ER's",
        "validator identity may be passed as the first remaining account;",
        "omitted, the delegation program picks one.",
      ],
      discriminator: [39, 6, 122, 70, 65, 76, 166, 26],
      accounts: [
        {
          name: "payer",
          signer: true,
        },
        {
          name: "buffer_pda",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "const",
                value: [98, 117, 102, 102, 101, 114],
              },
              {
                kind: "account",
                path: "pda",
              },
            ],
            program: {
              kind: "const",
              value: [
                176, 19, 252, 153, 174, 29, 63, 9, 201, 203, 137, 179, 81, 231, 32, 187,
                243, 140, 183, 251, 61, 108, 118, 234, 137, 194, 199, 179, 144, 52, 237,
                138,
              ],
            },
          },
        },
        {
          name: "delegation_record_pda",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "const",
                value: [100, 101, 108, 101, 103, 97, 116, 105, 111, 110],
              },
              {
                kind: "account",
                path: "pda",
              },
            ],
            program: {
              kind: "account",
              path: "delegation_program",
            },
          },
        },
        {
          name: "delegation_metadata_pda",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "const",
                value: [
                  100, 101, 108, 101, 103, 97, 116, 105, 111, 110, 45, 109, 101, 116, 97,
                  100, 97, 116, 97,
                ],
              },
              {
                kind: "account",
                path: "pda",
              },
            ],
            program: {
              kind: "account",
              path: "delegation_program",
            },
          },
        },
        {
          name: "pda",
          writable: true,
        },
        {
          name: "owner_program",
          address: "CrLS1Ry58q59AgmqbNVrqbfs2bWGJtjk12PezXh4LeYh",
        },
        {
          name: "delegation_program",
          address: "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh",
        },
        {
          name: "system_program",
          address: "11111111111111111111111111111111",
        },
      ],
      args: [
        {
          name: "creator",
          type: "pubkey",
        },
        {
          name: "room_id",
          type: "u64",
        },
      ],
    },
    {
      name: "emit_event",
      docs: [
        "Fire an ephemeral message. The payload is emitted as an event in the",
        "transaction logs and never written to any account — no rent, no state",
        "growth, still onchain-ordered. Clients receive it via a logsSubscribe",
        "on the room address. Membership is proven by the caller's presence",
        "slot; signed by the session key.",
      ],
      discriminator: [82, 133, 188, 136, 167, 139, 209, 52],
      accounts: [
        {
          name: "room",
          docs: [
            "contend. Listed in the transaction so `mentions` log filters on the",
            "room address match.",
          ],
        },
        {
          name: "presence",
        },
        {
          name: "signer",
          signer: true,
        },
      ],
      args: [
        {
          name: "name",
          type: "string",
        },
        {
          name: "data",
          type: "bytes",
        },
      ],
    },
    {
      name: "join_room",
      docs: [
        "Join a room: creates (or re-initializes) the caller's presence slot and",
        "registers `authority` — the ephemeral session key that will sign this",
        "player's realtime writes on the ER. Re-joining rotates the authority.",
        "",
        "The room is passed unchecked on purpose: it may already be delegated to",
        "an ER (owner = delegation program), which would fail Anchor's owner",
        "check. Join only needs its address for the presence seeds.",
      ],
      discriminator: [95, 232, 188, 81, 124, 130, 78, 139],
      accounts: [
        {
          name: "room",
        },
        {
          name: "presence",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "const",
                value: [112, 114, 101, 115, 101, 110, 99, 101],
              },
              {
                kind: "account",
                path: "room",
              },
              {
                kind: "account",
                path: "player",
              },
            ],
          },
        },
        {
          name: "player",
          writable: true,
          signer: true,
        },
        {
          name: "system_program",
          address: "11111111111111111111111111111111",
        },
      ],
      args: [
        {
          name: "authority",
          type: "pubkey",
        },
      ],
    },
    {
      name: "leave_room",
      docs: [
        "Leave: commit and undelegate the caller's presence slot. Signed by",
        "either the session authority (popup-free) or the joining wallet.",
      ],
      discriminator: [249, 42, 239, 128, 192, 20, 114, 156],
      accounts: [
        {
          name: "payer",
          writable: true,
          signer: true,
        },
        {
          name: "presence",
          writable: true,
        },
        {
          name: "magic_program",
          address: "Magic11111111111111111111111111111111111111",
        },
        {
          name: "magic_context",
          writable: true,
          address: "MagicContext1111111111111111111111111111111",
        },
      ],
      args: [],
    },
    {
      name: "process_undelegation",
      discriminator: [196, 28, 41, 206, 48, 37, 51, 167],
      accounts: [
        {
          name: "base_account",
          writable: true,
        },
        {
          name: "buffer",
          pda: {
            seeds: [
              {
                kind: "const",
                value: [
                  117, 110, 100, 101, 108, 101, 103, 97, 116, 101, 45, 98, 117, 102, 102,
                  101, 114,
                ],
              },
              {
                kind: "account",
                path: "base_account",
              },
            ],
            program: {
              kind: "const",
              value: [
                181, 183, 0, 225, 242, 87, 58, 192, 204, 6, 34, 1, 52, 74, 207, 151, 184,
                53, 6, 235, 140, 229, 25, 152, 204, 98, 126, 24, 147, 128, 167, 62,
              ],
            },
          },
        },
        {
          name: "payer",
          writable: true,
        },
        {
          name: "system_program",
          address: "11111111111111111111111111111111",
        },
      ],
      args: [
        {
          name: "account_seeds",
          type: {
            vec: "bytes",
          },
        },
      ],
    },
    {
      name: "set_presence",
      docs: [
        "Write the caller's own presence blob (cursor position, status, …).",
        "Per-player slots mean concurrent players never contend on one account.",
      ],
      discriminator: [255, 5, 233, 192, 250, 158, 66, 90],
      accounts: [
        {
          name: "presence",
          writable: true,
        },
        {
          name: "signer",
          signer: true,
        },
      ],
      args: [
        {
          name: "data",
          type: "bytes",
        },
      ],
    },
    {
      name: "set_state",
      docs: [
        "Write the shared room state. Any joined player may write; membership is",
        "proven by their presence slot, writes are signed by the session key.",
      ],
      discriminator: [65, 69, 101, 248, 20, 15, 200, 53],
      accounts: [
        {
          name: "room",
          writable: true,
        },
        {
          name: "presence",
        },
        {
          name: "signer",
          signer: true,
        },
      ],
      args: [
        {
          name: "data",
          type: "bytes",
        },
      ],
    },
    {
      name: "undelegate_room",
      docs: [
        "Commit and undelegate the room back to the base layer. Creator only —",
        "signed by the creator wallet (an occasional, popup-worthy action).",
      ],
      discriminator: [151, 179, 196, 11, 39, 232, 174, 131],
      accounts: [
        {
          name: "payer",
          writable: true,
          signer: true,
        },
        {
          name: "room",
          writable: true,
        },
        {
          name: "magic_program",
          address: "Magic11111111111111111111111111111111111111",
        },
        {
          name: "magic_context",
          writable: true,
          address: "MagicContext1111111111111111111111111111111",
        },
      ],
      args: [],
    },
  ],
  accounts: [
    {
      name: "Presence",
      discriminator: [255, 181, 116, 26, 172, 166, 141, 39],
    },
    {
      name: "Room",
      discriminator: [156, 199, 67, 27, 222, 23, 185, 94],
    },
  ],
  events: [
    {
      name: "RoomEvent",
      discriminator: [112, 70, 119, 238, 104, 126, 153, 227],
    },
  ],
  errors: [
    {
      code: 6000,
      name: "StateTooLarge",
      msg: "payload exceeds the account's fixed capacity",
    },
    {
      code: 6001,
      name: "NotAMember",
      msg: "presence slot does not belong to this room",
    },
    {
      code: 6002,
      name: "BadAuthority",
      msg: "signer is not the registered session authority",
    },
  ],
  types: [
    {
      name: "Presence",
      type: {
        kind: "struct",
        fields: [
          {
            name: "room",
            type: "pubkey",
          },
          {
            name: "player",
            type: "pubkey",
          },
          {
            name: "authority",
            type: "pubkey",
          },
          {
            name: "seq",
            type: "u64",
          },
          {
            name: "bump",
            type: "u8",
          },
          {
            name: "data",
            type: "bytes",
          },
        ],
      },
    },
    {
      name: "Room",
      type: {
        kind: "struct",
        fields: [
          {
            name: "creator",
            type: "pubkey",
          },
          {
            name: "room_id",
            type: "u64",
          },
          {
            name: "max_players",
            type: "u16",
          },
          {
            name: "seq",
            type: "u64",
          },
          {
            name: "bump",
            type: "u8",
          },
          {
            name: "state",
            type: "bytes",
          },
        ],
      },
    },
    {
      name: "RoomEvent",
      type: {
        kind: "struct",
        fields: [
          {
            name: "room",
            type: "pubkey",
          },
          {
            name: "player",
            type: "pubkey",
          },
          {
            name: "name",
            type: "string",
          },
          {
            name: "data",
            type: "bytes",
          },
        ],
      },
    },
  ],
} as const;
